export const CREDIT_PACKAGES = [
  {
    id: "1" as const,
    credits: 1,
    amountCents: 599,
    label: "1 diagnostic",
    priceLabel: "5,99 €",
    originalPrice: null as string | null,
    saving: null as string | null,
    badge: null as string | null,
    highlight: false,
  },
  {
    id: "3" as const,
    credits: 3,
    amountCents: 1599,
    label: "3 diagnostics",
    priceLabel: "15,99 €",
    originalPrice: "18,00 €",
    saving: "2 € d'économie",
    badge: "–12 %",
    highlight: false,
  },
  {
    id: "6" as const,
    credits: 6,
    amountCents: 2899,
    label: "6 diagnostics",
    priceLabel: "28,99 €",
    originalPrice: "36,00 €",
    saving: "7 € d'économie",
    badge: "–20 %",
    highlight: true,
  },
  {
    id: "10" as const,
    credits: 10,
    amountCents: 4199,
    label: "10 diagnostics",
    priceLabel: "41,99 €",
    originalPrice: "60,00 €",
    saving: "18 € d'économie",
    badge: "–30 %",
    highlight: false,
  },
] as const

export type CreditPackageId = (typeof CREDIT_PACKAGES)[number]["id"]
