/**
 * Modèles proposés dans les listes (diagnostic / vente).
 * Liste **étendue** (VP, SUV, utilitaires légers courants en Europe) — la finition / carrosserie
 * détaillée reste dans « Variante / finition » ou « Mon modèle n'apparaît pas ? ».
 */
export const carModels: Record<string, string[]> = {
  // Françaises
  Renault: [
    "Clio",
    "Megane",
    "Captur",
    "Kadjar",
    "Scenic",
    "Twingo",
    "Zoe",
    "Arkana",
    "Austral",
    "Espace",
    "Talisman",
    "Kangoo",
    "Master",
    "Trafic",
  ],
  Peugeot: [
    "208",
    "e-208",
    "308",
    "e-308",
    "408",
    "508",
    "2008",
    "e-2008",
    "3008",
    "5008",
    "Partner",
    "Rifter",
    "Expert",
    "Boxer",
  ],
  Citroën: [
    "C1",
    "C3",
    "C3 Aircross",
    "C4",
    "C4 X",
    "C5 X",
    "C5 Aircross",
    "Berlingo",
    "SpaceTourer",
    "Jumpy",
    "Jumper",
    "Ami",
  ],
  DS: ["DS 3", "DS 3 Crossback", "DS 4", "DS 7", "DS 9"],
  Alpine: ["A110", "A110 S", "A110 GT", "A110 R"],
  Bugatti: ["Chiron", "Veyron", "Divo", "Centodieci"],
  // Allemandes
  Volkswagen: [
    "Golf",
    "Polo",
    "Tiguan",
    "T-Roc",
    "T-Cross",
    "Passat",
    "Arteon",
    "Touareg",
    "ID.3",
    "ID.4",
    "ID.5",
    "ID.7",
    "ID. Buzz",
    "Touran",
    "Caddy",
    "Transporter",
  ],
  BMW: [
    "Série 1",
    "Série 2",
    "Série 3",
    "Série 4",
    "Série 5",
    "Série 7",
    "Série 8",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "iX",
    "iX3",
    "i4",
    "i5",
    "i7",
    "Z4",
  ],
  "Mercedes-Benz": [
    "Classe A",
    "Classe B",
    "Classe C",
    "Classe E",
    "Classe S",
    "CLA",
    "CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "EQA",
    "EQB",
    "EQC",
    "EQE",
    "EQS",
    "AMG GT",
  ],
  Audi: [
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q7",
    "Q8",
    "e-tron",
    "e-tron GT",
    "TT",
    "R8",
  ],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718 Cayman", "718 Boxster"],
  Opel: ["Corsa", "Astra", "Mokka", "Crossland", "Grandland", "Insignia", "Combo", "Vivaro", "Movano", "Zafira"],
  Smart: ["Fortwo", "Forfour", "#1", "#3"],
  Mini: ["Mini 3 portes", "Mini 5 portes", "Mini Clubman", "Mini Countryman", "Mini Cabrio", "Mini Electric"],
  // Italiennes
  Fiat: ["500", "500X", "500L", "Panda", "Tipo", "Punto", "Ducato", "Doblo", "Fiorino", "500e"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "Giulietta", "MiTo", "4C"],
  Ferrari: ["Roma", "Portofino", "F8 Tributo", "SF90 Stradale", "296 GTB", "812 Superfast", "Purosangue"],
  Lamborghini: ["Huracán", "Urus", "Revuelto", "Aventador"],
  Maserati: ["Ghibli", "Quattroporte", "Levante", "MC20", "Grecale", "GranTurismo"],
  Lancia: ["Ypsilon", "Delta", "Thema"],
  // Japonaises
  Toyota: [
    "Yaris",
    "Yaris Cross",
    "Corolla",
    "C-HR",
    "RAV4",
    "Highlander",
    "Land Cruiser",
    "Prius",
    "Camry",
    "Supra",
    "GR86",
    "Aygo X",
    "bZ4X",
    "Proace",
  ],
  Honda: ["Jazz", "Civic", "Accord", "HR-V", "CR-V", "ZR-V", "e:Ny1", "Honda e"],
  Nissan: ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "GT-R", "370Z", "Navara", "Townstar"],
  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "MX-30"],
  Suzuki: ["Swift", "Ignis", "Vitara", "S-Cross", "Jimny", "Across", "Swace"],
  Mitsubishi: ["Space Star", "ASX", "Eclipse Cross", "Outlander", "L200", "Pajero"],
  Subaru: ["Impreza", "XV", "Forester", "Outback", "BRZ", "Levorg", "Solterra"],
  Lexus: ["UX", "NX", "RX", "ES", "IS", "LC", "LS", "LBX", "RZ"],
  Infiniti: ["Q30", "Q50", "Q60", "QX30", "QX50", "QX70"],
  Daihatsu: ["Terios", "Sirion", "Materia"],
  // Coréennes
  Hyundai: ["i10", "i20", "i30", "Kona", "Tucson", "Santa Fe", "Ioniq 5", "Ioniq 6", "Bayon", "Nexo"],
  Kia: ["Picanto", "Rio", "Ceed", "Proceed", "XCeed", "Stonic", "Niro", "Sportage", "Sorento", "EV6", "EV9"],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  SsangYong: ["Tivoli", "Korando", "Rexton", "Musso"],
  // Américaines
  Ford: ["Fiesta", "Focus", "Puma", "Kuga", "Mustang", "Mustang Mach-E", "Explorer", "Ranger", "Transit", "Tourneo"],
  Chevrolet: ["Spark", "Cruze", "Malibu", "Camaro", "Corvette", "Trax", "Equinox", "Blazer", "Tahoe", "Silverado"],
  Dodge: ["Challenger", "Charger", "Durango", "Ram 1500"],
  Jeep: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator", "Avenger"],
  Cadillac: ["CT4", "CT5", "Escalade", "XT4", "XT5", "XT6", "Lyriq"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  Chrysler: ["300", "Pacifica", "Voyager"],
  GMC: ["Canyon", "Sierra", "Terrain", "Acadia", "Yukon", "Hummer EV"],
  Lincoln: ["Corsair", "Nautilus", "Aviator", "Navigator"],
  Buick: ["Encore", "Envision", "Enclave"],
  // Britanniques
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Range Rover",
    "Range Rover Sport",
    "Range Rover Velar",
    "Range Rover Evoque",
  ],
  Jaguar: ["XE", "XF", "F-Type", "E-Pace", "F-Pace", "I-Pace"],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga"],
  "Rolls-Royce": ["Ghost", "Phantom", "Wraith", "Dawn", "Cullinan", "Spectre"],
  "Aston Martin": ["Vantage", "DB11", "DB12", "DBS", "DBX"],
  McLaren: ["540C", "570S", "600LT", "720S", "765LT", "Artura"],
  Lotus: ["Elise", "Exige", "Evora", "Emira", "Eletre"],
  MG: ["MG3", "MG4", "MG5", "ZS", "HS", "Marvel R", "Cyberster"],
  // Suédoises
  Volvo: ["XC40", "XC60", "XC90", "S60", "S90", "V60", "V90", "C40 Recharge", "EX30", "EX90"],
  Saab: ["9-3", "9-5", "9-4X"],
  // Espagnoles
  Seat: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Mii"],
  Cupra: ["Born", "Formentor", "Leon", "Ateca", "Tavascan"],
  // Tchèques
  Skoda: ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  // Roumaines
  Dacia: ["Sandero", "Duster", "Jogger", "Spring", "Logan"],
  // Chinoises
  BYD: ["Atto 3", "Han", "Tang", "Seal", "Dolphin"],
  "Lynk & Co": ["01", "02", "03"],
  Polestar: ["Polestar 2", "Polestar 3", "Polestar 4"],
  NIO: ["ET5", "ET7", "EL6", "EL7"],
  Xpeng: ["G3", "P5", "P7", "G9"],
  Aiways: ["U5", "U6"],
  Geely: ["Coolray", "Atlas", "Tugella"],
}

export const carBrands = Object.keys(carModels).sort()
